clc;
clf; 
clear;
F = 50; 
Fs = 300; 
Ta = 1/F; 
t = 0:0.0001:5*Ta; 
xa = 3 * sin(100 * %pi * t);
subplot(3, 1, 1);
plot(t, xa);
title("Tin hieu tuong tu xa(t) = 3sin(100*pi*t) (5 chu ky)");
xlabel("t (s)"); 
ylabel("xa(t)");
n = 0:29;
xn = 3 * sin((%pi / 3) * n);
subplot(3, 1, 2);
plot2d3(n, xn); 
plot(n, xn, 'ro'); 
title("Tin hieu roi rac x(n) voi Fs = 300 mau/s (5 chu ky)");
xlabel("n"); 
ylabel("x(n)");
delta = 0.1;
xqn = floor(xn / delta) * delta;
subplot(3, 1, 3);
plot2d3(n, xqn);
plot(n, xqn, 'go'); 
title("Tin hieu luong tu hoa xq(n) cat cut voi delta = 0.1");
xlabel("n"); 
ylabel("xq(n)");
