clc;
clear;
nx = -2:1;
x = [1, -2, 3, 6];
ny1 = -1:2;
y1 = [6, 3, -2, 1];
ny2 = -5:-2;
y2 = [1, -2, 3, 6];
ny3 = -3:0;
y3 = [12, 6, -4, 2];
scf(1); clf;
subplot(2, 1, 1);
plot2d3(nx, x); plot(nx, x, 'ro');
title("Tin hieu goc x(n)");
xlabel("n"); ylabel("x(n)"); xgrid();
subplot(2, 1, 2);
plot2d3(ny1, y1); plot(ny1, y1, 'bo');
title("Tin hieu y1(n) = x(-n)");
xlabel("n"); ylabel("y1(n)"); xgrid();
scf(2); clf;
subplot(2, 1, 1);
plot2d3(nx, x); plot(nx, x, 'ro');
title("Tin hieu goc x(n)");
xlabel("n"); ylabel("x(n)"); xgrid();
subplot(2, 1, 2);
plot2d3(ny2, y2); plot(ny2, y2, 'bo');
title("Tin hieu y2(n) = x(n+3)");
xlabel("n"); ylabel("y2(n)"); xgrid();
scf(3); clf;
subplot(2, 1, 1);
plot2d3(nx, x); plot(nx, x, 'ro');
title("Tin hieu goc x(n)");
xlabel("n"); ylabel("x(n)"); xgrid();
subplot(2, 1, 2);
plot2d3(ny3, y3); plot(ny3, y3, 'bo');
title("Tin hieu y3(n) = 2*x(-n-2)");
xlabel("n"); ylabel("y3(n)"); xgrid();
